<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="38fn-ynar" name="dependsOnTest(failed)" tests="3" failures="1" timestamp="23 Nov 2018 17:57:33 GMT" time="0.094" errors="0">
  <testcase name="login" time="0.008" classname="testNG.DependsOnTest"/>
  <testcase name="logout" time="0.01" classname="testNG.DependsOnTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at testNG.DependsOnTest.logout(DependsOnTest.java:23)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- logout -->
  <testcase name="test2" time="0.0" classname="testNG.DependsOnTest">
    <skipped/>
  </testcase> <!-- test2 -->
</testsuite> <!-- dependsOnTest(failed) -->
