<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="70449" started-at="2019-05-04T20:47:09Z" finished-at="2019-05-04T20:48:19Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="70449" started-at="2019-05-04T20:47:09Z" finished-at="2019-05-04T20:48:19Z">
      <class name="Extentreport.Extentreport.Extent_rept_atmcly_TC_fail">
        <test-method status="PASS" signature="setup()[pri:0, instance:Extentreport.Extentreport.Extent_rept_atmcly_TC_fail@74ad1f1f]" name="setup" is-config="true" duration-ms="753" started-at="2019-05-04T20:47:09Z" finished-at="2019-05-04T20:47:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="loginTest()[pri:0, instance:Extentreport.Extentreport.Extent_rept_atmcly_TC_fail@74ad1f1f]" name="loginTest" duration-ms="65591" started-at="2019-05-04T20:47:10Z" finished-at="2019-05-04T20:48:15Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at Extentreport.Extentreport.Extent_rept_atmcly_TC_fail.loginTest(Extent_rept_atmcly_TC_fail.java:45)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:Extentreport.Extentreport.Extent_rept_atmcly_TC_fail@74ad1f1f]" name="tearDown" is-config="true" duration-ms="3996" started-at="2019-05-04T20:48:15Z" finished-at="2019-05-04T20:48:19Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginTest status=FAILURE method=Extent_rept_atmcly_TC_fail.loginTest()[pri:0, instance:Extentreport.Extentreport.Extent_rept_atmcly_TC_fail@74ad1f1f] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Extentreport.Extentreport.Extent_rept_atmcly_TC_fail -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
