<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="38fn-ynar" name="dependsOnTest" tests="3" failures="1" timestamp="22 Nov 2019 17:48:48 GMT" time="0.051" errors="0">
  <testcase name="login" time="0.01" classname="testNG.DependsOnTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at testNG.DependsOnTest.login(DependsOnTest.java:13)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- login -->
  <testcase name="logout" time="0.0" classname="testNG.DependsOnTest">
    <skipped/>
  </testcase> <!-- logout -->
  <testcase name="test2" time="0.0" classname="testNG.DependsOnTest">
    <skipped/>
  </testcase> <!-- test2 -->
</testsuite> <!-- dependsOnTest -->
