<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Failed suite [basicAnnotaions]" duration-ms="94" started-at="2018-11-23T17:57:33Z" finished-at="2018-11-23T17:57:33Z">
    <groups>
    </groups>
    <test name="dependsOnTest(failed)" duration-ms="94" started-at="2018-11-23T17:57:33Z" finished-at="2018-11-23T17:57:33Z">
      <class name="testNG.Allannotaions">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:testNG.Allannotaions@3e9b1010]" name="beforeSuite" is-config="true" duration-ms="17" started-at="2018-11-23T23:27:33Z" finished-at="2018-11-23T23:27:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:testNG.Allannotaions@3e9b1010]" name="beforeTest" is-config="true" duration-ms="5" started-at="2018-11-23T23:27:33Z" finished-at="2018-11-23T23:27:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:testNG.Allannotaions@3e9b1010]" name="afterTest" is-config="true" duration-ms="1" started-at="2018-11-23T23:27:33Z" finished-at="2018-11-23T23:27:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:testNG.Allannotaions@3e9b1010]" name="afterSuite" is-config="true" duration-ms="1" started-at="2018-11-23T23:27:33Z" finished-at="2018-11-23T23:27:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- testNG.Allannotaions -->
      <class name="testNG.DependsOnTest">
        <test-method status="PASS" signature="login()[pri:0, instance:testNG.DependsOnTest@6c3708b3]" name="login" duration-ms="8" started-at="2018-11-23T23:27:33Z" finished-at="2018-11-23T23:27:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="FAIL" signature="logout()[pri:0, instance:testNG.DependsOnTest@6c3708b3]" name="logout" duration-ms="10" started-at="2018-11-23T23:27:33Z" depends-on-methods="testNG.DependsOnTest.login" finished-at="2018-11-23T23:27:33Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at testNG.DependsOnTest.logout(DependsOnTest.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method status="SKIP" signature="test2()[pri:0, instance:testNG.DependsOnTest@6c3708b3]" name="test2" duration-ms="0" started-at="2018-11-23T23:27:33Z" depends-on-methods="testNG.DependsOnTest.logout, testNG.DependsOnTest.login" finished-at="2018-11-23T23:27:33Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method DependsOnTest.test2()[pri:0, instance:testNG.DependsOnTest@6c3708b3] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method DependsOnTest.test2()[pri:0, instance:testNG.DependsOnTest@6c3708b3] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
      </class> <!-- testNG.DependsOnTest -->
    </test> <!-- dependsOnTest(failed) -->
  </suite> <!-- Failed suite [basicAnnotaions] -->
</testng-results>
